version: "3"
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    environment:
      - WAIT_HOSTS=mongo
    ports:
      - "8181:8181"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: maxime
      MONGO_INITDB_ROOT_PASSWORD: 56964
    ports:
      - 8000:8000

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: maxime
      ME_CONFIG_MONGODB_ADMINPASSWORD: 56964
      ME_CONFIG_MONGODB_URL: mongodb://maxime:56964@mongo:8081/
