version: "3"
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    environment:
      - WAIT_HOSTS=mongo
    ports:
      - "8181:8181"

  reactnative:
    build:
      context: ./front-end
      dockerfile: Dockerfile.reactnative
    ports:
      - "19006:19006"
    depends_on:
      - backend
